spring.application.name=user-service
spring.config.import=optional:file:./secret.properties
spring.datasource.url=${DB_HOST}
spring.datasource.username=${DB_NAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.jpa.repositories.enabled=true
spring.jpa.properties.hibernate.ejb.naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.output.ansi.enabled=ALWAYS
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} %clr(%-5level){cyan} [%thread] %cyan(%logger{15}) - %msg%n
