spring.datasource.url=${SPRING_DATASOURCE_URL_DOCKER}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME_DOCKER}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD_DOCKER}

spring.data.redis.host=${SPRING_REDIS_HOST_DOCKER}
spring.data.redis.port=${SPRING_REDIS_PORT_DOCKER}

logging.level.org.springframework.web=DEBUG