spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.data.redis.host=${SPRING_REDIS_HOST}                                
spring.data.redis.port=${SPRING_REDIS_PORT}

logging.level.org.springframework.web=DEBUG